name: TodoSync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-14/1,22,23 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Branch Filestorage Action
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        branch: graphtoken
        path: graphtoken.asc
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./TodoSynchronizer.CLI/TodoSynchronizer.CLI.csproj
    - name: Build
      run: dotnet build ./TodoSynchronizer.CLI/TodoSynchronizer.CLI.csproj --no-restore -c Release
    - name: Run
      run: ./TodoSynchronizer.CLI/bin/Release/net6.0/TodoSynchronizer.CLI -canvastoken ${{ secrets.CANVAS_TOKEN }} -graphtokenfile graphtoken.asc -configfile config.yaml -graphtokenkey ${{ secrets.KEY }}
    - name: keep workflow alive
      uses: gautamkrishnar/keepalive-workflow@master
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
